#!/bin/bash
# Pulse Agent Deployment Script
# Generated by Prime Spark Engineering Team

set -e

echo "========================================"
echo "🫀 Deploying Pulse Agent"
echo "========================================"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

print_error() {
    echo -e "${RED}❌${NC} $1"
}

# Check if running on Pi 5
if [ ! -f /proc/device-tree/model ]; then
    print_warning "Not running on Raspberry Pi - proceeding anyway"
else
    MODEL=$(cat /proc/device-tree/model)
    echo "Device: $MODEL"
fi

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    print_error "Docker not installed. Please install Docker first."
    exit 1
fi

print_status "Docker found"

# Check if Docker Compose is available
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    print_error "Docker Compose not installed. Please install Docker Compose first."
    exit 1
fi

print_status "Docker Compose found"

# Load environment variables
if [ -f ../../.env ]; then
    print_status "Loading environment from .env"
    export $(cat ../../.env | grep -v '^#' | xargs)
else
    print_warning "No .env file found in prime-spark-ai root"
fi

# Stop existing containers
echo ""
echo "Stopping existing Pulse Agent containers..."
docker-compose down 2>/dev/null || true
print_status "Stopped existing containers"

# Build the image
echo ""
echo "Building Pulse Agent Docker image..."
docker-compose build
print_status "Docker image built"

# Start the services
echo ""
echo "Starting Pulse Agent..."
docker-compose up -d
print_status "Pulse Agent started"

# Wait for service to be ready
echo ""
echo "Waiting for Pulse Agent to be ready..."
sleep 5

# Check health
if curl -s -f http://localhost:8001/pulse/health > /dev/null 2>&1; then
    print_status "Pulse Agent is healthy and responding!"
else
    print_warning "Pulse Agent may not be ready yet. Check with: docker-compose logs pulse-agent"
fi

echo ""
echo "========================================"
echo "🫀 Pulse Agent Deployment Complete!"
echo "========================================"
echo ""
echo "📊 Access Points:"
echo "   - API:        http://localhost:8001"
echo "   - Health:     http://localhost:8001/pulse/health"
echo "   - Metrics:    http://localhost:8001/pulse/metrics"
echo "   - Nodes:      http://localhost:8001/pulse/nodes"
echo "   - Alerts:     http://localhost:8001/pulse/alerts"
echo ""
echo "🛠️  Management Commands:"
echo "   - View logs:  docker-compose logs -f pulse-agent"
echo "   - Stop:       docker-compose down"
echo "   - Restart:    docker-compose restart pulse-agent"
echo "   - Status:     docker-compose ps"
echo ""
echo "📈 Optional Monitoring Stack:"
echo "   - Start Prometheus & Grafana:"
echo "     docker-compose --profile monitoring up -d"
echo "   - Prometheus: http://localhost:9090"
echo "   - Grafana:    http://localhost:3000 (admin/admin)"
echo ""
echo "🔍 Quick Health Check:"
curl -s http://localhost:8001/pulse/health | python3 -m json.tool 2>/dev/null || echo "   (Pulse agent starting up...)"
echo ""
