"""
Prime Spark AI - System Telemetry Collector
Generated by Autonomous Completion Agent
"""

import asyncio
import psutil
from datetime import datetime
from typing import Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)


class TelemetryCollector:
    """
    Collect and stream system telemetry data
    """

    def __init__(
        self,
        device_id: str,
        kafka_manager=None,
        collection_interval: int = 30
    ):
        self.device_id = device_id
        self.kafka_manager = kafka_manager
        self.collection_interval = collection_interval
        self.running = False

    async def start_collection(self):
        """Start telemetry collection loop"""
        self.running = True
        logger.info(f"Starting telemetry collection for {self.device_id}")

        while self.running:
            try:
                metrics = await self.collect_metrics()
                await self.stream_metrics(metrics)
                await asyncio.sleep(self.collection_interval)
            except Exception as e:
                logger.error(f"Telemetry collection error: {e}")
                await asyncio.sleep(5)

    async def stop_collection(self):
        """Stop telemetry collection"""
        self.running = False
        logger.info("Stopping telemetry collection")

    async def collect_metrics(self) -> Dict[str, Any]:
        """Collect system metrics"""
        return {
            'cpu_percent': psutil.cpu_percent(interval=1),
            'memory_percent': psutil.virtual_memory().percent,
            'disk_percent': psutil.disk_usage('/').percent,
            'temperature': self._get_temperature(),
            'load_avg_1m': psutil.getloadavg()[0] if hasattr(psutil, 'getloadavg') else 0,
            'network_sent_mb': psutil.net_io_counters().bytes_sent / (1024 * 1024),
            'network_recv_mb': psutil.net_io_counters().bytes_recv / (1024 * 1024),
        }

    def _get_temperature(self) -> Optional[float]:
        """Get CPU temperature (Raspberry Pi specific)"""
        try:
            with open('/sys/class/thermal/thermal_zone0/temp') as f:
                temp = int(f.read()) / 1000.0
            return temp
        except:
            return None

    async def stream_metrics(self, metrics: Dict[str, Any]):
        """Stream metrics to Kafka"""
        if not self.kafka_manager:
            return

        try:
            await self.kafka_manager.send_message(
                topic='edge.telemetry',
                message={
                    'device_id': self.device_id,
                    'metrics': metrics,
                    'timestamp': datetime.now().isoformat()
                },
                key=self.device_id
            )
            logger.debug(f"Streamed metrics for {self.device_id}")
        except Exception as e:
            logger.error(f"Failed to stream metrics: {e}")
