#!/bin/bash
# Prime Spark AI - Automated Backup Script
# Generated by Autonomous Completion Agent

set -e

BACKUP_DIR="/mnt/nas/backups/prime-spark-ai"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo "Starting backup at $TIMESTAMP"

# Create backup directory
mkdir -p "$BACKUP_DIR/$TIMESTAMP"

# Backup Redis data
echo "Backing up Redis..."
docker exec prime-spark-redis redis-cli SAVE
docker cp prime-spark-redis:/data/dump.rdb "$BACKUP_DIR/$TIMESTAMP/redis.rdb"

# Backup PostgreSQL
echo "Backing up PostgreSQL..."
docker exec prime-spark-postgres pg_dumpall -U postgres > "$BACKUP_DIR/$TIMESTAMP/postgres.sql"

# Backup configuration files
echo "Backing up configurations..."
tar -czf "$BACKUP_DIR/$TIMESTAMP/configs.tar.gz" .env docker-compose*.yml

# Backup models
echo "Backing up models..."
if [ -d "models" ]; then
    tar -czf "$BACKUP_DIR/$TIMESTAMP/models.tar.gz" models/
fi

# Remove backups older than 30 days
find "$BACKUP_DIR" -type d -mtime +30 -exec rm -rf {} +

echo "Backup completed successfully"
